[package]
name = "ele"
version = "0.1.0"
authors = ["oshima <k.oshjma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = "0.3.4"
termios = "0.3"
unicode-width = "0.1.7"
